import React from "react";
import { formatDate } from "@/lib/utils";
import iecLogoPath from "/images/iec-logo.jpg";
import gdgLogoPath from "/images/gdg-logo.png";

type CertificateProps = {
  name: string;
  githubRepo: string;
  vercelDeployment: string;
  certificateId: string;
  date: string;
};

const Certificate = React.forwardRef<HTMLDivElement, CertificateProps>(
  ({ name, githubRepo, vercelDeployment, certificateId, date }, ref) => {
    return (
      <div ref={ref} className="certificate-container border-8 border-blue-100 rounded-2xl relative bg-white p-8 shadow-[0_35px_60px_-15px_rgba(0,0,0,0.1)]">
        <div 
          className="absolute top-0 left-0 w-full h-full bg-center bg-no-repeat opacity-5 rounded-xl" 
          style={{ 
            backgroundImage: `url(${iecLogoPath})`,
            backgroundSize: "300px",
            backgroundPosition: "center" 
          }}
        ></div>
        
        {/* Certificate Header with Logos */}
        <div className="text-center mb-8 relative">
          <div className="mb-4 flex justify-between">
            <img 
              src={iecLogoPath} 
              alt="IEC Logo" 
              className="h-16 w-16 object-contain" 
            />
            <img 
              src={gdgLogoPath} 
              alt="GDG Logo" 
              className="h-16 w-auto object-contain" 
            />
          </div>
          
          <div className="mb-2 mt-4">
            <h1 className="text-3xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 text-transparent bg-clip-text font-sans">Certificate of Completion</h1>
            <div className="h-1 w-32 bg-gradient-to-r from-blue-500 to-purple-500 mx-auto mt-2 rounded-full"></div>
          </div>
        </div>
        
        {/* Certificate Body */}
        <div className="text-center mb-10">
          <p className="text-gray-600 mb-4">This is to certify that</p>
          <p className="text-4xl font-bold text-gray-900 my-6 font-sans bg-gradient-to-r from-blue-700 to-purple-700 text-transparent bg-clip-text">{name}</p>
          <p className="text-gray-600">has successfully completed a web development project</p>
          <p className="text-gray-600 my-4">
            Project deployed at: <span className="text-blue-600 font-medium">{vercelDeployment}</span>
          </p>
          <p className="text-gray-600">
            GitHub Repository: <span className="text-blue-600 font-medium">{githubRepo}</span>
          </p>
        </div>
        
        {/* Certificate Footer */}
        <div className="mt-12 flex justify-between items-end">
          <div className="text-left">
            <div className="w-48 border-t-2 border-gray-400 pt-1">
              <p className="text-sm text-gray-600">Date</p>
              <p className="text-gray-900 font-medium">{date}</p>
            </div>
          </div>
          <div className="text-right">
            <div className="w-40 h-16 flex items-end justify-end mb-1">
              <div className="h-10 w-28 bg-gradient-to-r from-blue-600 to-purple-600 rounded-md opacity-70"></div>
            </div>
            <div className="w-48 border-t-2 border-gray-400 pt-1">
              <p className="text-sm text-gray-600">Director Signature</p>
              <p className="text-gray-900 font-medium">GDG IEC</p>
            </div>
          </div>
        </div>
        
        {/* Certificate ID */}
        <div className="mt-10 text-center">
          <p className="text-sm text-gray-500">Certificate ID: <span className="font-medium">{certificateId}</span></p>
          <p className="text-sm text-gray-500">Generated by GDG IEC Certificate Generator</p>
        </div>
      </div>
    );
  }
);

Certificate.displayName = "Certificate";

export default Certificate;
